"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronUp, CircleAlert, History, MessageSquareText, RotateCcw, Send, Sparkles, Target } from "lucide-react";
import PageShell from "@/components/PageShell";
import { AnalysisRecord, demoRecord, loadCurrent } from "@/lib/analysis-data";

type Q={cat:string;q:string;rate:string;goal:string;steps:string;framework:string;need:string;note:string};
const raw:[string,string,string][]=[
 ["跨专业与求职动机","为什么从原专业转向 AI？","92%"],["跨专业与求职动机","为什么选择 AI 产品，而不是算法？","86%"],["跨专业与求职动机","原专业能力如何迁移到 AI 产品？","82%"],
 ["个人项目","你的岗位识别项目解决了什么问题？","90%"],["个人项目","为什么需要区分硬门槛和可补能力？","84%"],["个人项目","岗位适配度是如何计算的？","80%"],["个人项目","为什么不全部使用大模型判断？","76%"],
 ["AI 产品基础","你的 Prompt 经过哪些迭代？","83%"],["AI 产品基础","你如何发现并修复 Badcase？","81%"],["AI 产品基础","RAG 和普通大模型问答有什么区别？","79%"],
 ["企业业务理解","为什么选择这家公司？","88%"],["企业业务理解","你如何理解公司的 AI 业务？","78%"],["企业业务理解","如何判断一个需求是否必须使用 AI？","74%"],
 ["场景分析与问题解决","知识库回答错误时如何定位？","85%"],["场景分析与问题解决","用户认为匹配结果不准确，你会如何优化？","77%"]
];
const questions:Q[]=raw.map(([cat,q,rate])=>({cat,q,rate,goal:cat==="个人项目"?"考察产品定义、方案取舍与数据意识。":cat==="跨专业与求职动机"?"判断转行动机是否真实，以及过往能力能否迁移。":cat==="企业业务理解"?"判断是否理解目标企业、客户和业务价值。":"考察 AI 产品基础、问题拆解与迭代能力。",steps:"第一句直接给结论；第二部分引用真实经历；第三部分连接目标岗位；第四部分说明下一步行动。",framework:"结论 → 真实证据 → 岗位关系 → 未来行动",need:"补充你亲自完成的项目任务、可量化结果和一次具体迭代。",note:"不要把 AI 描述成万能方案，不要编造未提供的实习、项目或业务结果。"}));

export default function InterviewPage(){
 const [record,setRecord]=useState<AnalysisRecord|null>(null);const [tab,setTab]=useState(0);const [open,setOpen]=useState<number|null>(0);const [mock,setMock]=useState(false);const [idx,setIdx]=useState(0);const [answer,setAnswer]=useState("");const [score,setScore]=useState(false);
 useEffect(()=>setRecord(loadCurrent()||demoRecord),[]);const cats=["全部","跨专业与求职动机","个人项目","AI 产品基础","企业业务理解","场景分析与问题解决"];const shown=tab===0?questions:questions.filter(x=>x.cat===cats[tab]);const reset=()=>{setMock(true);setIdx(0);setAnswer("");setScore(false)};
 if(!record)return <PageShell><div className="container py-24 muted">正在准备问题…</div></PageShell>;
 return <PageShell><section className="container py-12 sm:py-16">{!mock?<><div className="flex flex-wrap items-end justify-between gap-5"><div><span className="tag"><Sparkles size={14}/> {record.companyName} · {record.jobTitle}</span><h1 className="title mt-5">15 道高概率面试问题</h1><p className="muted mt-3">基于当前画像、JD 与模拟企业业务生成，不虚构你未提供的经历。</p><div className="mt-4 flex gap-3"><Link href="/report" className="btn-secondary"><ArrowLeft size={16}/>返回岗位报告</Link><Link href="/history" className="btn-secondary"><History size={16}/>历史记录</Link></div></div><button onClick={reset} className="btn-primary"><MessageSquareText size={18}/>开始模拟面试</button></div>
 <div className="mt-8 flex gap-2 overflow-x-auto pb-2">{cats.map((x,i)=><button key={x} onClick={()=>setTab(i)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab===i?"bg-[#2e3040] text-white":"border border-[#e1dfd9] bg-white text-[#686a74]"}`}>{x}{i>0&&` · ${questions.filter(q=>q.cat===x).length}`}</button>)}</div>
 <div className="mt-4 space-y-4">{shown.map(x=>{const global=questions.indexOf(x);const active=open===global;return <article key={x.q} className="card overflow-hidden"><button onClick={()=>setOpen(active?null:global)} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#eff0ff] font-black text-[#5a68d0]">{String(global+1).padStart(2,"0")}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-[#7a7d88]">{x.cat}</span><span className="tag !px-2 !py-1">预计 {x.rate}</span></div><h2 className="mt-2 text-base font-extrabold sm:text-lg">{x.q}</h2></div>{active?<ChevronUp/>:<ChevronDown/>}</button>{active&&<div className="animate-in border-t border-[#eceae5] bg-[#faf9f6] p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-2"><Detail icon={Target} title="考察目的" text={x.goal}/><Detail icon={ArrowRight} title="推荐回答结构" text={x.framework}/><Detail icon={CheckCircle2} title="详细答题步骤" text={x.steps}/><Detail icon={CircleAlert} title="回答注意事项" text={x.note} warn/></div><div className="mt-4 rounded-2xl border border-[#dfe1f5] bg-[#f2f3ff] p-4"><b className="text-sm text-[#525daf]">需要补充的个人信息</b><p className="muted mt-2 text-sm leading-6">{x.need}</p><p className="mt-3 text-xs text-[#838591]">参考答案仅提供结构：先直接回答结论，再引用你真实填写的专业、项目、技能与岗位信息；资料不足时不会生成虚构完整答案。</p></div></div>}</article>})}</div></>:
 <div className="mx-auto max-w-4xl animate-in"><button onClick={()=>setMock(false)} className="mb-6 flex items-center gap-2 text-sm font-bold text-[#60626c]"><ArrowLeft size={17}/>返回题目列表</button><div className="mb-4 flex items-center justify-between"><span className="font-bold text-[#5969dc]">模拟面试 · 第 {idx+1} 题</span><span className="muted text-sm">{idx+1} / {questions.length}</span></div><div className="progress mb-6"><i style={{width:`${(idx+1)/questions.length*100}%`}}/></div><div className="card p-6 sm:p-9"><span className="tag">{questions[idx].cat} · 被问概率 {questions[idx].rate}</span><h1 className="mt-5 text-2xl font-extrabold leading-9 sm:text-3xl">{questions[idx].q}</h1><p className="muted mt-3 text-sm">请只使用自己的真实项目与行动作答。</p><textarea value={answer} onChange={e=>{setAnswer(e.target.value);setScore(false)}} className="input mt-7 min-h-52 resize-y !p-5" placeholder="按“结论—真实证据—岗位关系—未来行动”组织回答……"/>{!score?<button disabled={!answer.trim()} onClick={()=>setScore(true)} className="btn-primary mt-4 disabled:opacity-40"><Send size={17}/>提交回答</button>:<div className="animate-in mt-5 rounded-3xl border border-[#dde0fb] bg-[#f2f3ff] p-5"><div className="flex flex-wrap items-center justify-between"><div><p className="text-sm font-bold text-[#626ab2]">模拟综合得分</p><p className="mt-1 text-4xl font-black text-[#4f5dc5]">78<span className="text-lg"> / 100</span></p></div><div className="flex gap-2"><span className="tag">相关性 82</span><span className="tag">逻辑 76</span><span className="tag">证据 68</span></div></div><p className="muted mt-4 text-sm">结构清楚；建议补充一项具体项目结果，并说明如何验证判断。</p></div>}</div><div className="mt-5 flex justify-between gap-3"><button onClick={reset} className="btn-secondary"><RotateCcw size={17}/>重新开始</button><button onClick={()=>{if(idx<questions.length-1){setIdx(idx+1);setAnswer("");setScore(false)}else setMock(false)}} className="btn-primary">{idx===questions.length-1?"结束模拟":"下一题"}<ArrowRight size={17}/></button></div></div>}
 </section></PageShell>
}
function Detail({icon:Icon,title,text,warn=false}:{icon:typeof Target;title:string;text:string;warn?:boolean}){return <div className={`rounded-2xl p-4 ${warn?"bg-[#fff3e9]":"bg-white"}`}><div className="flex items-center gap-2 text-sm font-extrabold"><Icon size={17} className={warn?"text-[#c86e3b]":"text-[#5969dc]"}/>{title}</div><p className="muted mt-2 text-sm leading-6">{text}</p></div>}
