"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, Building2, CalendarDays, CircleCheck, ExternalLink, Factory, History, MapPin, MessageSquareText, RotateCcw, ShieldCheck, Users } from "lucide-react";
import PageShell from "@/components/PageShell";
import { SectionCard } from "@/components/ReportUI";
import { AnalysisRecord, demoRecord, loadCurrent, resetCurrentAnalysis } from "@/lib/analysis-data";

const facts=[[Users,"企业规模","500–999 人"],[CalendarDays,"成立时间","2018 年"],[Factory,"所属行业","企业软件 / 智能制造"],[Building2,"发展阶段","C 轮融资"],[BriefcaseBusiness,"办公地址","创意产业园"]];
export default function CompanyPage(){const [record,setRecord]=useState<AnalysisRecord|null>(null);useEffect(()=>setRecord(loadCurrent()||demoRecord),[]);if(!record)return <PageShell><div className="container py-24 muted">正在读取当前记录…</div></PageShell>;
return <PageShell><section className="container py-12 sm:py-16"><div className="mb-8"><span className="tag"><ShieldCheck size={14}/> 当前为产品原型示例</span><h1 className="title mt-5">{record.companyName}</h1><p className="muted mt-2">目标岗位：{record.jobTitle} · {record.city}</p><div className="mt-4 rounded-2xl border border-[#dedff0] bg-[#f3f4ff] p-4 text-sm text-[#5c6091]">分析内容基于用户输入和模拟公开资料，不代表真实联网搜索结果。</div><div className="mt-5 flex flex-wrap gap-3"><Link href="/report" className="btn-secondary"><ArrowLeft size={16}/>返回岗位分析</Link><Link href="/interview" className="btn-primary"><MessageSquareText size={16}/>进入面试准备</Link><Link href="/history" className="btn-secondary"><History size={16}/>历史记录</Link><Link href="/profile" onClick={()=>resetCurrentAnalysis()} className="btn-secondary"><RotateCcw size={16}/>新的测试</Link></div></div>
<div className="grid gap-5 lg:grid-cols-3"><SectionCard title="企业基本信息" className="lg:col-span-2"><div className="grid gap-3 sm:grid-cols-2">{[...facts,[MapPin,"所在城市",record.city]].map(([Icon,l,v])=>{const I=Icon as typeof Users;return <div className="soft-card flex gap-3 p-4" key={String(l)}><I size={19} className="text-[#5969dc]"/><div><p className="text-xs text-[#888a93]">{String(l)}</p><b className="mt-1 block">{String(v)}</b></div></div>})}</div></SectionCard><SectionCard title="一句话看懂"><p className="leading-7 text-[#60626c]">该企业的模拟业务画像是：{record.companyResearch.business}，并把知识库与 AI 助手嵌入业务流程。</p><div className="mt-5 flex flex-wrap gap-2"><span className="tag">B2B</span><span className="tag">企业服务</span><span className="tag">企业 AI</span></div></SectionCard>
<SectionCard title="业务与产品" className="lg:col-span-3"><div className="grid gap-6 md:grid-cols-3"><Info title="主要业务" text={record.companyResearch.business}/><Info title="AI 方向" text={record.companyResearch.aiDirection}/><Info title="目标客户" text="中大型企业的业务、运营和信息化团队"/></div></SectionCard>
<SectionCard title="目标岗位可能参与的业务" className="lg:col-span-2"><div className="space-y-4"><Info title="近期业务方向" text="围绕业务文档、服务记录与行业知识构建企业知识库，降低信息获取成本。"/><Info title="岗位参与方式" text={`作为${record.jobTitle}，可能参与需求梳理、知识库产品流程、模型回答测试与 Badcase 优化。`}/></div></SectionCard><SectionCard title="岗位与业务关系"><div className="relative space-y-2 before:absolute before:bottom-3 before:left-[11px] before:top-3 before:w-px before:bg-[#d9dcef]">{["理解企业业务场景","整理知识与需求","设计 AI 产品方案","验证回答效果"].map((x,i)=><div className="relative flex items-center gap-3 text-sm font-semibold" key={x}><span className="z-10 grid size-6 place-items-center rounded-full bg-[#e9ebff] text-[10px] text-[#5363cf]">{i+1}</span>{x}</div>)}</div></SectionCard>
<SectionCard title="典型候选人能力画像" className="lg:col-span-3"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["常见学历","本科及以上"],["高频专业","理工、经管、设计"],["高频技能","PRD、RAG、数据分析"],["常见项目","知识库 / AI 应用"],["业务能力","需求拆解与沟通"]].map(([l,v])=><div className="soft-card p-4" key={l}><p className="text-xs text-[#888a93]">{l}</p><p className="mt-2 font-bold leading-6">{v}</p></div>)}</div><p className="muted mt-5 text-xs">不分析员工性别、年龄或任何与岗位能力无关的私人特征。</p></SectionCard>
<SectionCard title="面试前应该了解的业务问题" className="lg:col-span-3"><div className="grid gap-3 md:grid-cols-3">{["企业为什么需要知识库？","业务人员在什么场景使用 AI 助手？","回答正确率与响应速度如何取舍？"].map(x=><div className="flex gap-3 rounded-2xl border border-[#e7e4de] bg-white p-4" key={x}><CircleCheck size={19} className="shrink-0 text-[#5969dc]"/><span className="font-semibold leading-6">{x}</span></div>)}</div><div className="mt-5 flex items-center gap-2 text-xs text-[#8a8b93]"><ExternalLink size={13}/>信息来源为模拟公开资料，仅作产品功能演示</div></SectionCard></div></section></PageShell>}
function Info({title,text}:{title:string;text:string}){return <div><p className="text-sm font-extrabold">{title}</p><p className="muted mt-2 text-sm leading-7">{text}</p></div>}
